apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
  - managedByLabel
  - originAnnotations

namespace: weechat
commonLabels:
  app.kubernetes.io/name: weechat

configMapGenerator:
  - name: weechat
    files:
      - config/buflist.conf
      - config/fset.conf
      - config/irc.conf  
      - config/logger.conf  
      - config/relay.conf  
      - config/sec.conf
      - config/weechat.conf

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: weechat
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: /opt/kustomize/ksops
    files:
      - secrets.enc.k8s.yaml

resources:
  - ../../base/weechat
