apiVersion: v1
kind: Secret
metadata:
    name: softserve-clone
    annotations:
        tekton.dev/git-0: softserve.softserve.svc
type: kubernetes.io/ssh-auth
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:LW47ywnvV3OnQ7d1k6ASEVsr3PAkEwhXUtOZFr74zakOZO1zsSoziMo7rAtgbLTMeSHRj7wZJtioLnNY0iqkW4pt15d73NIMz8CWxdBMJr32WZph4bFPa9r0Tal6i8zJ4GSf1euy9u5awYhwUpVyerXfP7r/CcYwlZAo6dU+oIHpNPkzVOXDXAynwgu6jY6+zhIq52ZR3PhnQ7VzUzAmWBoIx+XsQxEgeinXMlVpN6v9Q5kBCGwXnoX8bYAn/uhHlDaJxAeLsfcwZovc+uGhbrOAoyoAkpT7s8xVW9p6e/nC5SRxxRWVRZWGH39uJTVUGrbY8QX5S+tKzdp3J3Zxiwarw5VTuuu6Mhx6nNlTQy5ZEugAYcRfR7NYaX/+OTkPs0X9zXaoXMEu02gCe14gxGGwnarEAzQwwkldlGOMwNucebzsID0lkXXeWgm4rHhJSHucdnbFLlqsDIB1wyfZOyzpKrRBbnx+tMkT+98d9J5nNUkC014mOP91Ad/vSGShkQ39fSRNM8CGEv2gUhQl,iv:+Augjo3BNW11Mces39wEW1vjTFMr/uEor2Owe9mVXZQ=,tag:TyZdZxEW7uD7rXpZtSXfhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZEVBMVB1eXB2R1RKb2Nl
            TUVuc2RZWGVnSER3blFLaThKQ0dvN2JYeDBRCjkvellCUDVybm55NTcrVlFJSXhN
            OUdYdXU1Nk9CQ3dpdzV4bzE2b3psR2sKLS0tIGVCVXg0d1MyMStwMFhQWGhjbGdC
            K2JIUUdOS3JhY2hZRC9ZNGIrQXpLeUEKcR/c0WIIpK7jjrb2yozIlVDMizkW+v1H
            3sHRXw4RO643/a5XcKMGPXtcEVZWqUqazY4+PJBh7aRnhbnhgZ5X/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T16:27:12Z"
    mac: ENC[AES256_GCM,data:mUR3ow3IuLK9q4EC5x6tEHkBz1zw0Sl0q6Q43uQ6p5BO9gv8fP9dsg+6BCNJeS8hv+VsqnSo5bb9Vd+SLiSlVRxxDAhxn/GKD3DdifCNB96lvrjVPf3eedLVfnb5c7SImS0b1RO7FYbd6d067VqGHgXh4APhzUZNPf/JVgHnZl8=,iv:JR/o8RI0oCEsFBshrAEYiV/oiIomijGUQQ6i+l7Qzjk=,tag:axWE58gn13Y7mgJQpkk3Aw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-publish
    annotations:
        tekton.dev/docker-0: https://ghcr.io
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:7a8M1+Af9n0fmw==,iv:bA/rXvBaLNldyMjr/lMRE0JxBmoiRbNQI7NgyKe+l+s=,tag:E15/ilzrLs/nRH5XJ6Opvg==,type:str]
    password: ENC[AES256_GCM,data:Awj6MqsIyGrd6tZGtJHwwo+tnMbq+kjzq8cXSEESY7mB/K1qLVgsvQ==,iv:Pnx9gnOqneuZfE/TZRuCM5B3lXBV9KzEsuQrm3CJn/I=,tag:aoDejHT2XYaq+l52qj67rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZEVBMVB1eXB2R1RKb2Nl
            TUVuc2RZWGVnSER3blFLaThKQ0dvN2JYeDBRCjkvellCUDVybm55NTcrVlFJSXhN
            OUdYdXU1Nk9CQ3dpdzV4bzE2b3psR2sKLS0tIGVCVXg0d1MyMStwMFhQWGhjbGdC
            K2JIUUdOS3JhY2hZRC9ZNGIrQXpLeUEKcR/c0WIIpK7jjrb2yozIlVDMizkW+v1H
            3sHRXw4RO643/a5XcKMGPXtcEVZWqUqazY4+PJBh7aRnhbnhgZ5X/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T16:27:12Z"
    mac: ENC[AES256_GCM,data:mUR3ow3IuLK9q4EC5x6tEHkBz1zw0Sl0q6Q43uQ6p5BO9gv8fP9dsg+6BCNJeS8hv+VsqnSo5bb9Vd+SLiSlVRxxDAhxn/GKD3DdifCNB96lvrjVPf3eedLVfnb5c7SImS0b1RO7FYbd6d067VqGHgXh4APhzUZNPf/JVgHnZl8=,iv:JR/o8RI0oCEsFBshrAEYiV/oiIomijGUQQ6i+l7Qzjk=,tag:axWE58gn13Y7mgJQpkk3Aw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: gcp-firebase
stringData:
    sa.json: ENC[AES256_GCM,data:Kjm6WvQDTo177uoFlEOTjt1rRF0Vfhak6PNGhfdV057I268HxolZmhqAxhjBK6HvlM1HPuGO2YI1KIicrn8Q+U9SoEZILZcp8LKfbp0+KEOga0Yk2qcqFcRM1StYB/ZTZoIe83ueApfR3RMfFOPZwq2s6Mridrx1xMSlDJWkxGn10T2q+H3aqAiiC5rketWrZondPKovPNJTNLR7wXdw7oedWfS5Dvj1+i2NZatHCrdfIlsHpZly7uk/tO+/0bskfcuuHV9hQ0Mk5VjHrHfo84uMEJO95U+3/b8COqUsY2Lm6CpfDhTFfNuatU2onuF1DB5QwUGj/Mz1yRAx/9SL996zD2qSbpScdiu/tXZBySitSejroYVM80Uu8VJcGrVjHAcMAQxM9TKEyYLRYs+Tr229TsvfjpdR8EGhz6B+NgLRERymMb9tgkczOnvS/PguJ88Abzt8Are0PWFN9lOQ9hsm9zvZ7SZ6WWNVVxabr5R6Tmw37UG5l3K/WAZtkZuNDxNVFo/R6fmuSkgPLtUKGXmRTXMtt8Ffg9x2hIsFyr7iXHefsWf8OBUkyqsa19jZqpIZ3+LAmDTGSrHtqlcQo2r9wBlVXT5ve5XgIzm5TNDxxxgEphuyIvMRYCYuGjcJmSbrj6OsYW/4kBlBCembq9+pWMHj+iuI4BM9z/IQtOgZejg+NAM8IwJmkM09bLT2JtZqbgLIzZNNY5yMevdHC7SyOOA5bOlGb9G1xeV4opETASMrfCohhJY22995vrd0vfo+6k+F90o6EbGts+bIlfuNXeykYKCGQ5Qn6XSpJgkypo2exHaAE0oqey/fiiTjAFGXK8aY5k1vGQikMFaKv7oGZ1vcMhwgktB/tDe7We1kQGUpBP2Zq6c4hbWl8k/dUWCZDJlGItrey66BqMbGcN4JI41nOHlAYSJCWvIgaSUAMb7cDMmXD/bsKoHsFOwhkSAcPkJta23WZ0rYb/4lpoDi/WHYWeFa2ZwFfgjUAmBe6C/IehjVfMl3taFMsD+bjMnmOxBNkvUd4P6E1iROp6JzlPEhP3uX9gYB0oeHW8a1zzkByGB+1kiF9E6lEMmGXVKFI+zKi3qRtLlpm4whoQYqBXjG2qOjd23KZYnoPHG4r6lxMqXoECAD61ED/vbq0onuIc00pykTgdDVh16po5xkkDgDMx9z3XwBM69dBTbsJJTKofJKFabgn5g6WWQ4q74iC7ffGqaYdIzXbOT5n3XzOvIut5Xpx+cei8JeoyBURVr6xJLOskC96jIng45oVdGARDGbIC9IK4mMUmKa2AiXiPipvknJ7dOZWLu90yX+sGl3cyvjtF0TODhKD6Vw4E5UUKlVZzInb5V3iGmw7gjZ+R7IZPvosaaty6eOYFiVvFM4W8F5JfRp6N4XhUWq+shyLOteIo+RN2zOU5ckecQlBoG6dPNl18UJjL0V3Akk9Wnc4lx7+Qn4CH+1SjGYGeMyDHFp9749/FBX31l1GJ+SR9GGBkFZtCcQbL5OC5WYV4/siiVZvld6yQFoGkwH0oGKV58KLja4gXkYM+XzGU0DvzIn0fwvaHH8dwXVwxu9zKvd73fhDUyrlAU5YAWVbearWpE3UCbgXIMec/qjDKbID2izAdSfHZbBgmKWjKqU277zfA4W8YQmqdkryRiZwaWVcoAYrshjkTJOnEr9Wgj0Tyt6R8pFMtc/CNoGk85C2hEBNUUutqF3IagdOGCUv/OsPYIqAfyXHqKhxYqYG3YPtFojLoLHeCSfrtHCPezIfBRP0Msxb/rMuiKZIbFMm0xngvZOH0mN6UM3ZFGoX3ZEYR74+H8yZXoMKU0KPczXFvfrniKcKW4vdI2FmHqSoh17hlBD1j70Oqa/Wmf3mUSUTqCzZeRdJ+sZpPwCDX3Ye79zWD2KCuSRk0Qdsbg3JqWnip38NcDVjbZq+c6psLDm3I/RbfqVp96ATHLInJ8iMhQZyrF4Gb7ymbeZOL8nqlhj4tI7iz6f69OwSHfTTtwSqTG83i9ATkU+0oNGysKImOfA99yx7gBA3U4VQ6fShoruPS0bsnDo1vCwWDP6GiEHhPWzFGIqsNM2edKuyphZFwFbJxx8+o1ZgN80GWCxMdBgsp5ccuWMHq/rtm/UDLwng/Fd1PGZ994MBOz6pClQ0zEK4GEnYVdFawoy9jXadSXzsxodP7vBs2L8V/K5pi+10QE+10hByoy0JHYsogapMV7+Z0yxNDchVvs8EX1uL+poLFZIcp8As2N6Qe/08OqzcOp0hNtpbJfzML3pnn3cA6Gx5enZZYkIy1hDG0fN+JNynVZKKyuaa9ww1fLKEBc48qROYlg0F7AWmh5bFmU+YQn1wSTjmJ0KuxpdDxZqfmBWwmC+AUHLLYsDyj2R6sZaF8sEpGS598YILM+IA8+kXuBp98lVtCeVqyMRrTyUqO/H7eC1y9Od+gW20C0G949aEirHwa2JZjEjlB8iahM0tkVFngdlbxiHgwrgVqBB1fLHEBlu7qLv4HCWuq0lPBQ/2Psm5YyCU83RIW5w8A5SOlJwQq8aoZTJ+q9eV5kC1ZI6SsTr6CnIfKYEM3pCDrvF79qp/5KhRegrfY1lB6Z/VOUmyjPsOizyrfzJF67DIBxC8BQfapfOkZEERQmN37RfvRIi5WCO1SJ0be8BsABJptFrcSRVzpcjDDXqjk/f8Z+FcTCs1aBpjNjei+jate6WsrvzIWt+T/tEpBD91un1TwNlcM8GVITzjWZV7c32J7EUjxbpjSnt9XwrcPAJfkbla47OI7dQXL0mhGjmm4A5+hTQP/lC+Z3oKy+A81frUtuy01v07nIvhXlecXkFZF1LPGOh1RcgfkdsSq4rLvJzqIAqv4lbWBO0r9IWJ/QGyY1lAODcdXIy4VFt045t+d6lgBhA5aTHAvEU+FfStt1rumCKE70SFbowaq7Wsoy4nopMHO4hiSMzdfwb21bWpJM8/WekLJIKqMDWHTxZ5UhxtCjZ8tJ1j3RSeyFwgCw7xawIASInUqUje5CR9CSPwHC0X2ViQWpyLrkchNX+4CeB3nOBXgpwR0xXUV84WYAjs0nQH6HtaUIClKvJ3aeeFvL5bRACieGnou00q2y0JbHQlOnbnSd2vcKIe9hvHRn8Tj4wWMJ0DVlLwnwud55kjQUkhP5nBMg1cf/8+A==,iv:Q/UBRgYR0EGzkrm0Exb7DYwNHtOwNNF2H8Ko3KyIexM=,tag:9aLVogus1Rrv4fiDGbDSEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZEVBMVB1eXB2R1RKb2Nl
            TUVuc2RZWGVnSER3blFLaThKQ0dvN2JYeDBRCjkvellCUDVybm55NTcrVlFJSXhN
            OUdYdXU1Nk9CQ3dpdzV4bzE2b3psR2sKLS0tIGVCVXg0d1MyMStwMFhQWGhjbGdC
            K2JIUUdOS3JhY2hZRC9ZNGIrQXpLeUEKcR/c0WIIpK7jjrb2yozIlVDMizkW+v1H
            3sHRXw4RO643/a5XcKMGPXtcEVZWqUqazY4+PJBh7aRnhbnhgZ5X/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T16:27:12Z"
    mac: ENC[AES256_GCM,data:mUR3ow3IuLK9q4EC5x6tEHkBz1zw0Sl0q6Q43uQ6p5BO9gv8fP9dsg+6BCNJeS8hv+VsqnSo5bb9Vd+SLiSlVRxxDAhxn/GKD3DdifCNB96lvrjVPf3eedLVfnb5c7SImS0b1RO7FYbd6d067VqGHgXh4APhzUZNPf/JVgHnZl8=,iv:JR/o8RI0oCEsFBshrAEYiV/oiIomijGUQQ6i+l7Qzjk=,tag:axWE58gn13Y7mgJQpkk3Aw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.0
