apiVersion: v1
kind: Secret
metadata:
    name: softserve-clone
    annotations:
        tekton.dev/git-0: softserve.softserve.svc
type: kubernetes.io/ssh-auth
stringData:
    ssh-privatekey: ENC[AES256_GCM,data:LW47ywnvV3OnQ7d1k6ASEVsr3PAkEwhXUtOZFr74zakOZO1zsSoziMo7rAtgbLTMeSHRj7wZJtioLnNY0iqkW4pt15d73NIMz8CWxdBMJr32WZph4bFPa9r0Tal6i8zJ4GSf1euy9u5awYhwUpVyerXfP7r/CcYwlZAo6dU+oIHpNPkzVOXDXAynwgu6jY6+zhIq52ZR3PhnQ7VzUzAmWBoIx+XsQxEgeinXMlVpN6v9Q5kBCGwXnoX8bYAn/uhHlDaJxAeLsfcwZovc+uGhbrOAoyoAkpT7s8xVW9p6e/nC5SRxxRWVRZWGH39uJTVUGrbY8QX5S+tKzdp3J3Zxiwarw5VTuuu6Mhx6nNlTQy5ZEugAYcRfR7NYaX/+OTkPs0X9zXaoXMEu02gCe14gxGGwnarEAzQwwkldlGOMwNucebzsID0lkXXeWgm4rHhJSHucdnbFLlqsDIB1wyfZOyzpKrRBbnx+tMkT+98d9J5nNUkC014mOP91Ad/vSGShkQ39fSRNM8CGEv2gUhQl,iv:+Augjo3BNW11Mces39wEW1vjTFMr/uEor2Owe9mVXZQ=,tag:TyZdZxEW7uD7rXpZtSXfhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14mg08panez45c6lj2cut2l8nqja0k5vm2vxmv5zvc4ufqgptgy2qcjfmuu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZEVBMVB1eXB2R1RKb2Nl
            TUVuc2RZWGVnSER3blFLaThKQ0dvN2JYeDBRCjkvellCUDVybm55NTcrVlFJSXhN
            OUdYdXU1Nk9CQ3dpdzV4bzE2b3psR2sKLS0tIGVCVXg0d1MyMStwMFhQWGhjbGdC
            K2JIUUdOS3JhY2hZRC9ZNGIrQXpLeUEKcR/c0WIIpK7jjrb2yozIlVDMizkW+v1H
            3sHRXw4RO643/a5XcKMGPXtcEVZWqUqazY4+PJBh7aRnhbnhgZ5X/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T11:49:18Z"
    mac: ENC[AES256_GCM,data:zD++Sp4vsEhoIxh/Vkc3qZSbSFRUfb+cKZ5Tz5I5EO7H9QBB8aSYdTnmWtyBPcoF4HfWA/XPu8Ja8LoosNxS8qmFxM7pugLoTFjTdb0aEUEbd6CwJBhNVsfNZK/s8FmIhII860QcVDRPHX3eceVm9W1c2t0aGWIp2B2+OiHm/wQ=,iv:9a/iD7cvxz/tm9d0nQAPY0bxFthZMzr6pH+LkER2H38=,tag:f9na7shpgMyHCWuSqMsLOw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.0
