apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ko-container
spec:
  displayName: Go Library
  description: |
    basic build / test / lints for a go module
  params:
    - name: reponame
      type: string
    - name: url
      type: string
      description: |
        url to clone git repo from
    - name: revision
      type: string
      default: main
      description: |
        revision to checkout
  workspaces:
    - name: cloned-repo
      description: |
        workspace for holding the cloned repo
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: cloned-repo
    - name: ko-container
      runAfter:
        - fetch-source
      taskRef:
        name: ko-container
      params:
        - name: reponame
          value: $(params.reponame)
      workspaces:
        - name: module
          workspace: cloned-repo
