apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: blogengine
spec:
  displayName: blogengine
  description: |
    basic and publish a static site
  params:
    - name: url
      type: string
      description: |
        url to clone git repo from
    - name: revision
      type: string
      default: main
      description: |
        revision to checkout
  workspaces:
    - name: cloned-repo
      description: |
        workspace for holding the cloned repo
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: cloned-repo
    - name: publish
      runAfter:
        - fetch-source
      taskRef:
        name: blogengine
      workspaces:
        - name: module
          workspace: cloned-repo
