apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: go-build-test
spec:
  displayName: "Build and test a Go Module"
  description: |
    build and test a go module with tip
  stepTemplate:
    image: "ghcr.io/seankhliao/go:tip-arm64"
    workingDir: "$(workspaces.module.path)"
    env:
      - name: GOFLAGS
        value: "-trimpath '-ldflags=-s -w' -buildvcs=false"
      - name: CGO_ENABLED
        value: "0"
      - name: GOMODCACHE
        value: /volumes/gomodcache
      - name: GOCACHE
        value: /volumes/gobuildcache
      - name: GOPROXY
        value: "http://goproxy.goproxy.svc.cluster.local,https://proxy.golang.org,direct"
    volumeMounts:
      - name: gomodcache
        mountPath: /volumes/gomodcache
      - name: gobuildcache
        mountPath: /volumes/gobuildcache
  steps:
    - name: version
      script: |
        go version
    - name: build
      script: |
        go build ./...
    - name: staticcheck
      script: |
        staticcheck ./...
    - name: test
      script: |
        go test -vet=all ./...
  volumes:
    - name: gomodcache
      emptyDir: {}
    - name: gobuildcache
      emptyDir: {}
  workspaces:
    - name: module
