apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-library
spec:
  displayName: Go Library
  description: |
    basic build / test / lints for a go module
  params:
    - name: url
      type: string
      description: |
        url to clone git repo from
    - name: revision
      type: string
      default: main
      description: |
        revision to checkout
  workspaces:
    - name: cloned-repo
      description: |
        workspace for holding the cloned repo
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: cloned-repo
    - name: build-test
      runAfter:
        - fetch-source
      taskSpec:
        displayName: "Build and test a Go Module"
        description: |
          build and test a go module with tip
        stepTemplate:
          image: "ghcr.io/seankhliao/go:tip-arm64"
          workingDir: "$(workspaces.module.path)"
          env:
            - name: GOFLAGS
              value: "-trimpath '-ldflags=-s -w' -buildvcs=false"
            - name: CGO_ENABLED
              value: "0"
            - name: GOMODCACHE
              value: /volumes/gomodcache
            - name: GOCACHE
              value: /volumes/gobuildcache
          volumeMounts:
            - name: gomodcache
              mountPath: /volumes/gomodcache
            - name: gobuildcache
              mountPath: /volumes/gobuildcache
        steps:
          - name: version
            script: |
              go version
          - name: build
            script: |
              go build ./...
          - name: staticcheck
            script: |
              staticcheck ./...
          - name: test
            script: |
              go test -vet=all ./...
        volumes:
          - name: gomodcache
            emptyDir: {}
          - name: gobuildcache
            emptyDir: {}
        workspaces:
          - name: module
      workspaces:
        - name: module
          workspace: cloned-repo
