apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: softserve-blogengine
  labels:
    event-listener: listener
spec:
  interceptors:
    - ref:
        name: cel
      params:
        - name: "filter"
          value: 'body.tektonPipeline == "blogengine"'
        - name: "overlays"
          value:
            - key: repourl
              expression: '"git+ssh://tekton-ihwa@softserve.softserve.svc/REPO.git".replace("REPO", body.repo)'
            - key: shortrev
              expression: body.commit.truncate(7)
  # bind object values to pramater names
  bindings:
    - name: reponame
      value: $(body.repo)
    - name: repourl
      value: $(extensions.repourl)
    - name: revision
      value: $(body.commit)
    - name: shortrev
      value: $(extensions.shortrev)
  # stamp out objects
  template:
    spec:
      params:
        - name: reponame
        - name: revision
        - name: repourl
        - name: shortrev
        - name: pipeline
      resourcetemplates:
        - apiVersion: tekton.dev/v1
          kind: PipelineRun
          metadata:
            generateName: $(tt.params.reponame)-$(tt.params.shortrev)-
          spec:
            pipelineRef:
              name: blogengine
            params:
              - name: revision
                value: $(tt.params.revision)
              - name: url
                value: $(tt.params.repourl)
            taskRunSpecs:
              - pipelineTaskName: fetch-source
                serviceAccountName: softserve-clone
            workspaces:
              - name: cloned-repo
                volumeClaimTemplate:
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 1Gi
