apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: weechat
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

resources:
- deployment.k8s.yaml
- namespace.k8s.yaml
- persistentvolumeclaim.k8s.yaml
