apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weechat
commonLabels:
  app.kubernetes.io/name: weechat

resources:
  - apps_v1__deployment____weechat.yaml
  - v1__namespace____weechat.yaml
  - v1__persistentvolumeclaim____weechat.yaml
