apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weechat
  labels:
    app.kubernetes.io/name: weechat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
