apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: envoy-gateway
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

resources:
  - install.yaml
