apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazelremote
  labels:
    app.kubernetes.io/name: bazelremote
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazelremote
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazelremote
    spec:
      enableServiceLinks: false
      containers:
      - name: bazel-remote-cache
        image: docker.io/buchgr/bazel-remote-cache:v2.4.3
        env:
        - name: BAZEL_REMOTE_DIR
          value: /data
        - name: BAZEL_REMOTE_MAX_SIZE
          value: "40" # GiB
        ports:
        - containerPort: 9092
          name: grpc
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          grpc:
            service: /grpc.health.v1.Health/Check
            port: 9092
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          grpc:
            service: /grpc.health.v1.Health/Check
            port: 9092
          failureThreshold: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bazelremote
