apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bazelremote
commonLabels:
  app.kubernetes.io/name: bazelremote

resources:
  - apps_v1__deployment____bazelremote.yaml
  - v1__namespace____bazelremote.yaml
  - v1__persistentvolumeclaim____bazelremote.yaml
  - v1__service____bazelremote.yaml
