apiVersion: v1
kind: Service
metadata:
  name: bazelremote
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
    appProtocol: HTTP
  - name: grpc
    port: 9092
    targetPort: grpc
    appProtocol: GRPC
  selector:
    app.kubernetes.io/name: bazelremote
