apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale
commonLabels:
  app.kubernetes.io/name: tailscale

resources:
  - apps_v1__deployment__tailscale__operator.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tailscale-operator.yaml
  - rbac_authorization_k8s_io_v1__clusterrolebinding____tailscale-operator.yaml
  - rbac_authorization_k8s_io_v1__role__tailscale__operator.yaml
  - rbac_authorization_k8s_io_v1__role__tailscale__proxies.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tailscale__operator.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tailscale__proxies.yaml
  - v1__namespace____tailscale.yaml
  - v1__serviceaccount__tailscale__operator.yaml
  - v1__serviceaccount__tailscale__proxies.yaml
