apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale
commonLabels:
  app.kuberentes.io/name: tailscale
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

resources:
  - manifests.yaml
