apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-system
commonLabels:
  app.kubernetes.io/name: gateway-api
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

resources:
  - experimental-install.yaml
