apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: goproxy
        annotations:
          tailscale.com/hostname: goproxy-ihwa
      spec:
        type: LoadBalancer
        loadBalancerClass: tailscale

resources:
  - ../../base/goproxy
