apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
  - managedByLabel
  - originAnnotations

patches:
  # - target:
  #     kind: ConfigMap
  #     name: resolvers-feature-flags
  #     namespace: tekton-pipelines-resolvers
  #   patch: |
  #     - op: replace
  #       path: /data/enable-bundles-resolver
  #       value: "false"
  - target:
      kind: ConfigMap
      name: feature-flags
      namespace: tekton-pipelines
    patch: |
      - op: replace
        path: /data/enable-api-fields
        value: "alpha"
  - target:
      kind: ConfigMap
      name: config-tracing
      namespace: tekton-pipelines
    patch: |
      - op: replace
        path: /data/enabled
        value: "true"
      - op: replace
        path: /data/endpoint
        value: http://ingest.otelcol.svc.cluster.local:14268/api/traces


resources:
  - ../../base/tekton-pipelines
  - ../../base/tekton-triggers
