apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: tekton-pipelines

resources:
  - admissionregistration_k8s_io_v1__mutatingwebhookconfiguration____webhook.pipeline.tekton.dev.yaml
  - admissionregistration_k8s_io_v1__validatingwebhookconfiguration____config.webhook.pipeline.tekton.dev.yaml
  - admissionregistration_k8s_io_v1__validatingwebhookconfiguration____validation.webhook.pipeline.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____clustertasks.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____customruns.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____pipelineruns.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____pipelines.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____resolutionrequests.resolution.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____taskruns.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____tasks.tekton.dev.yaml
  - apiextensions_k8s_io_v1__customresourcedefinition____verificationpolicies.tekton.dev.yaml
  - apps_v1__deployment__tekton-pipelines-resolvers__tekton-pipelines-remote-resolvers.yaml
  - apps_v1__deployment__tekton-pipelines__tekton-events-controller.yaml
  - apps_v1__deployment__tekton-pipelines__tekton-pipelines-controller.yaml
  - apps_v1__deployment__tekton-pipelines__tekton-pipelines-webhook.yaml
  - autoscaling_v2__horizontalpodautoscaler__tekton-pipelines__tekton-pipelines-webhook.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tekton-aggregate-edit.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tekton-aggregate-view.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tekton-events-controller-cluster-access.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tekton-pipelines-controller-cluster-access.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tekton-pipelines-controller-tenant-access.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tekton-pipelines-resolvers-resolution-request-updates.yaml
  - rbac_authorization_k8s_io_v1__clusterrole____tekton-pipelines-webhook-cluster-access.yaml
  - rbac_authorization_k8s_io_v1__clusterrolebinding____tekton-events-controller-cluster-access.yaml
  - rbac_authorization_k8s_io_v1__clusterrolebinding____tekton-pipelines-controller-cluster-access.yaml
  - rbac_authorization_k8s_io_v1__clusterrolebinding____tekton-pipelines-controller-tenant-access.yaml
  - rbac_authorization_k8s_io_v1__clusterrolebinding____tekton-pipelines-resolvers.yaml
  - rbac_authorization_k8s_io_v1__clusterrolebinding____tekton-pipelines-webhook-cluster-access.yaml
  - rbac_authorization_k8s_io_v1__role__tekton-pipelines-resolvers__tekton-pipelines-resolvers-namespace-rbac.yaml
  - rbac_authorization_k8s_io_v1__role__tekton-pipelines__tekton-pipelines-controller.yaml
  - rbac_authorization_k8s_io_v1__role__tekton-pipelines__tekton-pipelines-events-controller.yaml
  - rbac_authorization_k8s_io_v1__role__tekton-pipelines__tekton-pipelines-info.yaml
  - rbac_authorization_k8s_io_v1__role__tekton-pipelines__tekton-pipelines-leader-election.yaml
  - rbac_authorization_k8s_io_v1__role__tekton-pipelines__tekton-pipelines-webhook.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines-resolvers__tekton-pipelines-resolvers-namespace-rbac.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines__tekton-events-controller-leaderelection.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines__tekton-pipelines-controller-leaderelection.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines__tekton-pipelines-controller.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines__tekton-pipelines-events-controller.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines__tekton-pipelines-info.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines__tekton-pipelines-webhook-leaderelection.yaml
  - rbac_authorization_k8s_io_v1__rolebinding__tekton-pipelines__tekton-pipelines-webhook.yaml
  - v1__configmap__tekton-pipelines-resolvers__bundleresolver-config.yaml
  - v1__configmap__tekton-pipelines-resolvers__cluster-resolver-config.yaml
  - v1__configmap__tekton-pipelines-resolvers__config-leader-election.yaml
  - v1__configmap__tekton-pipelines-resolvers__config-logging.yaml
  - v1__configmap__tekton-pipelines-resolvers__config-observability.yaml
  - v1__configmap__tekton-pipelines-resolvers__git-resolver-config.yaml
  - v1__configmap__tekton-pipelines-resolvers__hubresolver-config.yaml
  - v1__configmap__tekton-pipelines-resolvers__resolvers-feature-flags.yaml
  - v1__configmap__tekton-pipelines__config-defaults.yaml
  - v1__configmap__tekton-pipelines__config-events.yaml
  - v1__configmap__tekton-pipelines__config-leader-election.yaml
  - v1__configmap__tekton-pipelines__config-logging.yaml
  - v1__configmap__tekton-pipelines__config-observability.yaml
  - v1__configmap__tekton-pipelines__config-registry-cert.yaml
  - v1__configmap__tekton-pipelines__config-spire.yaml
  - v1__configmap__tekton-pipelines__config-tracing.yaml
  - v1__configmap__tekton-pipelines__feature-flags.yaml
  - v1__configmap__tekton-pipelines__pipelines-info.yaml
  - v1__namespace____tekton-pipelines-resolvers.yaml
  - v1__namespace____tekton-pipelines.yaml
  - v1__secret__tekton-pipelines__webhook-certs.yaml
  - v1__service__tekton-pipelines-resolvers__tekton-pipelines-remote-resolvers.yaml
  - v1__service__tekton-pipelines__tekton-events-controller.yaml
  - v1__service__tekton-pipelines__tekton-pipelines-controller.yaml
  - v1__service__tekton-pipelines__tekton-pipelines-webhook.yaml
  - v1__serviceaccount__tekton-pipelines-resolvers__tekton-pipelines-resolvers.yaml
  - v1__serviceaccount__tekton-pipelines__tekton-events-controller.yaml
  - v1__serviceaccount__tekton-pipelines__tekton-pipelines-controller.yaml
  - v1__serviceaccount__tekton-pipelines__tekton-pipelines-webhook.yaml
