apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: softserve
commonLabels:
  app.kubernetes.io/name: softserve
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

resources:
  - namespace.k8s.yaml
  - deployment.k8s.yaml
