apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zot
    spec:
      enableServiceLinks: false
      containers:
      - name: zot
        image: ghcr.io/project-zot/zot-minimal-linux-arm64:v1.4.3
        args:
        - serve
        - /etc/zot/config.yaml
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - mountPath: /etc/zot
          name: config
        - mountPath: /data
          name: data
      volumes:
      - name: config
        configMap:
          name: zot
      - name: data
        persistentVolumeClaim:
          claimName: zot
