apiVersion: v1
kind: ConfigMap
metadata:
  name: zot
data:
  config.yaml: |
    distSpecVersion: "1.0.1"
    http:
      address: 0.0.0.0
      port: 8080
    log:
      level: info
    storage:
      rootDirectory: /data
      commit: true
      dedupe: true
      gc: true
      gcDelay: "1h"
      gcInterval: "12h"
