apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: wildcard-letsencrypt
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: /opt/kustomize/ksops
    files:
      - secrets.enc.k8s.yaml

resources:
  - ../../base/envoy-gateway
  - ../../base/gateway-api
  - gateway.k8s.yaml
