apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
  - managedByLabel
  - originAnnotations

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: wildcard-letsencrypt
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: /opt/kustomize/ksops
    files:
      - secrets.enc.k8s.yaml

resources:
  - ../../base/envoy-gateway
  - ../../base/gateway-api
  - gateway_networking_k8s_io_v1beta1__gateway__envoy-gateway-system__default.yaml
  - gateway_networking_k8s_io_v1beta1__gatewayclass____envoyproxy.yaml
