receivers:
  otlp:
    protocols:
      grpc:

  prometheus:
    config:
      scrape_configs:
        - job_name: "otelcol"
          scrape_interval: 5s
          static_configs:
            - targets:
                - "0.0.0.0:8888"

processors:

exporters:
  logging:

  otlp/lightstep:
    endpoint: ingest.lightstep.com:443
    headers:
      "lightstep-access-token": "${LIGHTSTEP_ACCESS_TOKEN}"

  otlp/honeycomb:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${X_HONEYCOMB_TEAM}"

  googlecloud:
    retry_on_failure:
      enabled: false

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions:
    - health_check
    - pprof
    - zpages

  pipelines:
    metrics:
      receivers:
        - prometheus
        - otlp
      exporters:
        - logging
        - otlp/lightstep

    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - otlp/lightstep
        - otlp/honeycomb
        - googlecloud

  telemetry:
    logs:
      level: warn
    metrics:
      level: detailed
      address: 0.0.0.0:8888
