apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
spec:
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
  template:
    spec:
      enableServiceLinks: false
      containers:
        - name: otelcol
          image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.83.0
          args:
            - --config=file:/etc/otelcol/config.yaml
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/gcp/serviceaccount.json
          envFrom:
            - secretRef:
                name: otelcol
          ports:
            - name: pprof
              containerPort: 1777
            - name: otlp
              containerPort: 4317
            - name: healthcheck
              containerPort: 13133
            - name: zpages
              containerPort: 55679
          startupProbe:
            httpGet:
              path: /
              port: healthcheck
          livenessProbe:
            httpGet:
              path: /
              port: healthcheck
          readinessProbe:
            httpGet:
              path: /
              port: healthcheck
          volumeMounts:
            - mountPath: /etc/otelcol
              name: config
            - mountPath: /var/run/secrets/gcp
              name: gcp
      volumes:
        - name: config
          configMap:
            name: otelcol
        - name: gcp
          secret:
            secretName: gcp

