apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otelcol
commonLabels:
  app.kubernetes.io/name: otelcol

configMapGenerator:
  - name: otelcol
    files:
      - config.yaml

resources:
  - apps_v1__deployment____otelcol.yaml
  - v1__namespace____otelcol.yaml
  - v1__service____ingest.yaml
