apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otelcol
commonLabels:
  app.kubernetes.io/name: otelcol
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

configMapGenerator:
  - name: otelcol
    files:
      - config.yaml

resources:
  - deployment.k8s.yaml
  - namespace.k8s.yaml
  - service.k8s.yaml
