apiVersion: v1
kind: Service
metadata:
  name: ingest
spec:
  type: ClusterIP
  ports:
  - name: otlp
    port: 4317
  - name: jaeger-grpc
    port: 14250
  - name: jaeger-thrift-http
    port: 14268
  selector:
    app.kubernetes.io/name: otelcol
