apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goproxy
commonLabels:
  app.kubernetes.io/name: goproxy

resources:
  - apps_v1__deployment____goproxy.yaml
  - v1__namespace____goproxy.yaml
  - v1__persistentvolumeclaim____goproxy.yaml
  - v1__service____goproxy.yaml
